### ISSUE TITLE
Pickling?

### ISSUE THREAD

**Issue by zflamig** [mortacious/numba-kdtree#17]
Is there any way to pickle these objects? It would be great for supporting parallel computations with joblib, etc. 

The creation time isn't actually that big a deal, but I'd prefer a way to have shared memory across processes which pickling enables. The trees I am planning to make are quiet large and having to keep copies in memory for each worker process will quickly be prohibitive.

**Comment by mortacious** [comment]
This is actually possible without major problems :). I already had a half-finished pickling support laying around and have just completed it. In the latest version (0.2.0) pickle should work as for any python object:

```python
kdtree = KDTree(data, **kwargs)
serialized_tree = pickle.dumps(kdtree)
restored_kdtree = pickle.loads(serialized_tree)
``` 

Note that here, same as with scipy's `ckdtree`, the data array will be serialized as well.
