### ISSUE TITLE
KDTree creation within numba functions

### ISSUE THREAD

**Issue by ushr-eperez** [mortacious/numba-kdtree#24]
I'm trying to create the KDTree object within a njit'd function, however I'm getting an error: 

No implementation of function Function(<function KDTree at 0x000001F704A18CA0>) found for signature:
 
 >>> KDTree(array(float64, 2d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'KDTree_numba': File: numba_kdtree\kd_tree.py: Line 481.
    With argument(s): '(array(float64, 2d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in function ascontiguousarray>) found for signature:
    
    >>> ascontiguousarray(OptionalType(array(float64, 2d, C)))
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'array_ascontiguousarray': File: numba\np\arrayobj.py: Line 4812.
           With argument(s): '(OptionalType(array(float64, 2d, C)))':
          Rejected as the implementation raised a specific error:
            TypingError: The argument "a" must be array-like
     raised from ..\..\\lib\site-packages\numba\np\arrayobj.py:4815
   
   During: resolving callee type: Function(<built-in function ascontiguousarray>)
   During: typing of call at ..\..\lib\site-packages\numba_kdtree\kd_tree.py (510)
   
   
   File "..\..\..\..\..\..\numba_kdtree\kd_tree.py", line 510:
       def KDTree_impl(data, leafsize=10, compact=False, balanced=False, root_bbox=None):
           <source elided>
               # compute the bounding box
           root_bbox = np.ascontiguousarray(root_bbox).astype(conv_dtype)
           ^

It would be very useful to have the ability to make a KDTree within a njit'd function, but I understand if the typing restrictions completely prevent this from happening.

**Comment by mortacious** [comment]
fixed in #25.
