### ISSUE TITLE
generated_jit deprecated (numba 0.57) and removed in the upcoming release (0.59)

### ISSUE THREAD

**Issue by milisims** [mortacious/numba-kdtree#27]
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-generated-jit

Any chance that this could be updated to work with the current numba release candidate?

**Comment by mortacious** [comment]
I was already aware of the problem and have fixed it just now! There should be no more `Deprecationwarning`s in the next version.
