### ISSUE TITLE
return_sorted: Unexpected behavior

### ISSUE THREAD

**Issue by workphone-002** [mortacious/numba-kdtree#30]
According to the documentation:
`return_sorted: Return the neighbors sorted by distance. Defaults to False.`

However, either I am not fully understanding the functionality of this argument, or the behavior is not as desired, since the indexes are NOT returned in order:

```
>>> test_points = np.array([[1,2],[73,19],[0,3],[4,9],[10,2],[24,3],[1,9],[56,8]])
>>> tree = numba_kdtree.KDTree(test_points)
>>> tree.query_radius(test_points[0],r=100],return_sorted=True)[0]
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)
```

The result is not ordered by distance. 
The expected result would be:

```
>>> np.linalg.norm(test_points-test_points[0],axis=-1).argsort()
array([0, 2, 6, 3, 4, 5, 7, 1], dtype=int64)
```

**Comment by mortacious** [comment]
Hey, this is actually just an oversight in the documentation :). The behavior is consistent with the original implementation in scipy. If `return_sorted=True` the function returns the sorted indices instead of the indices sorted by distance.

For comparison:

```python
from scipy.spatial import cKDTree
test_points = np.array([[1,2],[73,19],[0,3],[4,9],[10,2],[24,3],[1,9],[56,8]])
tree = cKDTree(test_points)
res = tree.query_ball_point(test_points[0], r=100, return_sorted=True)
print(res)
```
returns the same indices `[0, 1, 2, 3, 4, 5, 6, 7]`.

**Comment by workphone-002** [comment]
Thanks for the clarification
However, when return_sorted=False no indices by distance are returned either:

```
>>> tree.query_radius(test_points[0],r=100, return_sorted=False)[0]
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int64)
```

I've checked and the original behavior in scipy seems to be the same.
I don't understand the functionality of return_sorted, whether it is True or False, the indexes are not returned sorted by distance.

**Comment by mortacious** [comment]
The `query_radius`/`query_ball_point` functions  never return the indices sorted by distance. Due to an optimization in the C++-Code the function does not even compute most of the distances.
