### ISSUE TITLE
request for more distance metrics or help implementing my own

### ISSUE THREAD

**Issue by Gilnore** [mortacious/numba-kdtree#32]
Hello, are there any plans to make other distance metrics like the ones Sklean have? If not then is there any way I can implement my own distances?

**Comment by mortacious** [comment]
Hi, implementing other metrics is currently not planned, but i can give you a starting point at least:

The underlying C++ implementation is based on `scipy`s `ckdtree`. The distance metrics are based on the minkowski-p-norm which can be selected with the parameter `p` in all query functions. So the manhattan (p=1), euclidean (p=2), chebychev (p=inf) and all other minkowski metrics are supported out of the box. 

Other metrics are non-trivial to add though. All distance metrics are currently implemented as classes in the file
[src/ckdtree/distance_base.h](https://github.com/mortacious/numba-kdtree/blob/master/src/ckdtree/distance_base.h) and used as template parameters in the query functions selected with an if/else chain (e.g. [here](https://github.com/mortacious/numba-kdtree/blob/master/src/ckdtree/query.cpp#L423)). So to add additional metrics you‘ll have to implement them as classes and add them in these if/else chains. Additionally, you would have to make the new metrics selectable, which requires propagating them though all interfaces in c++, c and of course the ctypes-wrappers ([here](https://github.com/mortacious/numba-kdtree/blob/master/numba_kdtree/ckdtree.py#L82)) and numba functions ([here](https://github.com/mortacious/numba-kdtree/blob/master/numba_kdtree/kd_tree.py#L371)) in python.

**Comment by Gilnore** [comment]
awesome! I didn't know about the p-parameter, I'll try that out first. Thanks!

**Comment by Gilnore** [comment]
I see, so everything I need is included. This is wonderful, thanks for telling me!
